# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_horchata_small_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='horchata',
            name='tweet',
            field=models.URLField(default=datetime.datetime(2016, 3, 31, 5, 21, 16, 168254, tzinfo=utc), verbose_name='Tweet url'),
            preserve_default=False,
        ),
    ]
