# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_horchata_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horchata',
            name='tweet',
            field=models.URLField(editable=False, null=True, verbose_name='Tweet url'),
        ),
    ]
