# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160331_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horchata',
            name='tweet',
            field=models.CharField(editable=False, max_length=140, null=True, verbose_name='Tweet id'),
        ),
    ]
