# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160331_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='horchata',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='horchata',
            name='lon',
            field=models.FloatField(default=0, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='horchata',
            name='map_url',
            field=models.URLField(null=True, verbose_name='URL mapa'),
        ),
    ]
