# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160331_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horchata',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
